// <auto-generated />
namespace Angjobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added2tblsClients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added2tblsClients));
        
        string IMigrationMetadata.Id
        {
            get { return "201411071149378_added2tblsClients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
