// <auto-generated />
namespace Angjobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class alterFieldSize3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterFieldSize3));
        
        string IMigrationMetadata.Id
        {
            get { return "201506121121255_alterFieldSize3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
